### PR TITLE
Extend method length limit from 10 (default) to 12

### PR DESCRIPTION
**Pull request by mpelzsherman**
There are a few methods in rnr_ui that are 11 lines long. I don't think these methods would benefit from extracting code into a separate method. I think 12 is a more reasonable hard limit.

### CODE REVIEW

**Comment by dillo** [comment]
@mpelzsherman  Just curious, why the increase?

**Comment by dillo** [comment]
i'd recommend adding the following to methods that rubocop complains about before increasing the line limit. However, if you feel that it must be done then I'd prefer a conversation with some of our engineers before finalizing it.

def foo # rubocop:disable Metrics/MethodLength
  bar = 'something'
  ... ... ...
end

**Comment by mpelzsherman** [comment]
I can add exceptions to those methods, but I would rather increase the limit slightly.

Which engineers would you like to add to the conversion? @pasha ?

**Comment by dillo** [comment]
@pasha ^^^ would like your input on this.

**Comment by dillo** [comment]
cc @michaelstalker  ^^

**Comment by michaelstalker** [comment]
I don't have a strong preference one way or another.

**Comment by pasha** [comment]
I personally do not see a good reason for the rest of the team to use new change just because rnr_ui has many cases.  You still have a choice in your local project to control settings.  And why not 14 or 16?

**Comment by dillo** [comment]
@mpelzsherman I think you're good to merge.

**Comment by mpelzsherman** [comment]
Thanks @pasha. I'll add the exceptions.

**Pull request closed without merging**
