### PR TITLE
Use #detect instead of chaining methods

### PR DESCRIPTION
**Pull request by michaelstalker**

### CODE REVIEW

**Comment by mneumark** [comment]
:+1:  Makes cleaner code and is more efficient.

**Comment by Teapane** [comment]
:+1:

**Comment by michaelstalker** [comment]
:+1:

**Comment by pasha** [comment]
:+1:

**Comment by c0** [comment]
:+1:

**Comment by lfender6445** [comment]
Would it be preferable to keep enabled cops in the yml file with examples so we are not constantly updating the README?

**Comment by michaelstalker** [comment]
My preference would be to keep the README up to date, even though it's extra work. There are styles in there that RuboCop can't enforce.

**Pull request merged**
