### PR TITLE
Use #size for counting array and hash elements

### PR DESCRIPTION
**Pull request by michaelstalker**

### CODE REVIEW

**Comment by mneumark** [comment]
I struggled with this one for a while because `#count` is in `Enumerable` and `#size` is not. However, `#size` is typically O(1) where-as `#count` is typically O(n) (it is in `Enumerable`), so I give this a :+1:

**Comment by michaelstalker** [comment]
I could go either way. I don't think people will notice a difference in speed unless the collection is huge, and our collections usually aren't. Allowing people to choose between `#count` and `#size` gives them the freedom to be a bit more expressive in their code.

**Comment by pasha** [comment]
:+1:

**Comment by abouius** [comment]
:+1:

**Comment by lfender6445** [comment]
please update this branch as well as others.

**Comment by michaelstalker** [comment]
@lfender6445: I updated the branch to remove merge conflicts.

**Comment by lfender6445** [comment]
:+1:

**Comment by michaelstalker** [comment]
We should wait until people are done voting today before we merge any of these. Let's not revert the merge unless the team's vote says we should, though.

**Pull request merged**
