### PR TITLE
[MPN] [0000000000] Added Target Ruby Version

### PR DESCRIPTION
**Pull request by mneumark**
Added a Target Ruby version so that rubocop is run correctly.

### CODE REVIEW

**Comment by colinrymer** [comment]
Any reason to target 2.2 instead of 2.3?

**Comment by colinrymer** [comment]
After my question above is answered, I'm in favor of merging this. :+1:

**Comment by mneumark** [comment]
Because all our repos currently use 2.2....? I'd love to upgrade to 2.3, the lonely operator is awesome!

**Comment by colinrymer** [comment]
Is there any harm in targeting 2.3 while using 2.2?

**Comment by colinrymer** [comment]
(also, we can always update this to 2.3 later, so I wouldn't hold off on merging)

**Comment by mneumark** [comment]
I figured I'd leave it at that until we decide to start upgrading....Seemed logical to me....

**Comment by lfender6445** [comment]
👍

**Comment by martinstreicher** [comment]
we want to aim for 2.3.1.

**Pull request merged**
